version: '3.8'

services:
  api:
    build: ./server
    container_name: rds-campervan-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Monta só o código-fonte e mantém os node_modules do container
    - ./server:/app
    - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: rds-campervan-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rds-campervan-web
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - api


volumes:
  mongo-data:

