services:
  api:
    build: .
    container_name: rds-campervan-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Monta só o código-fonte e mantém os node_modules do container
    - .:/app
    - /app/node_modules

    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: rds-campervan-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
